apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cf-workloads
  labels:
    app: acmefit
    service: frontend
spec:
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: acmefit
    service: frontend
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: cf-workloads
  labels:
    app: acmefit
    service: frontend
spec:
  selector:
    matchLabels:
      app: acmefit
      service: frontend
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: acmefit
        service: frontend
    spec:
      containers:
      - image: rhardt/shopping.svc-2
        name: frontend
        env:
        - name: FRONTEND_PORT
          value: '3000'
        - name: USERS_HOST
          value: 'users.mesh.acme.internal.k10s.io'
        - name: CATALOG_HOST
          value: 'catalog.mesh.acme.internal.k10s.io'
        - name: ORDER_HOST
          value: 'order.mesh.acme.internal.k10s.io'
        - name: CART_HOST
          value: 'cart.mesh.acme.internal.k10s.io'
        - name: USERS_PORT
          value: '8083'
        - name: CATALOG_PORT
          value: '8082'
        - name: CART_PORT
          value: '5000'
        - name: ORDER_PORT
          value: '6000'
        ports:
        - containerPort: 3000
          name: frontend